### ISSUE TITLE
A Typo in the paper

### ISSUE THREAD

**Issue by xrc10** [RevanthRameshkumar/CRD3#1]
Thanks for sharing this interesting dataset! 

When preprocessing the dataset, I found a typo in your [paper](https://www.aclweb.org/anthology/2020.acl-main.459.pdf). For the filtering criteria, it should be 2 ≤ |tj:k| ≤ 100 instead of 2 < |tj:k| ≤ 100. Otherwise I cannot get the reported number of pairs after filtering (34243).

**Comment by RevanthRameshkumar** [comment]
Hey thanks for reporting! I'll take a look and update.

**Comment by RevanthRameshkumar** [comment]
Hey you are correct, I double checked the code and the data to make sure we did include the 2 😄
